name: termux
on: 
  schedule:
     - cron: '0 4 * * *'


jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - name: "Cloning repo" 
          uses: actions/checkout@v2

        - name: "Free additional disk space on host"
          run: |
                bash cleaner.sh

        - name: "Apt update"
          env:
              BOT: ${{ secrets.KCUBETERM_GIT_BOT_API }}
              
          run: |
                sudo apt update 
                rm -f kshsusnskzjz


        - name: "Get termux.txt"
          run: |
                wget https://raw.githubusercontent.com/kcubeterm/kcubeterm/master/lol.zip
                unzip -oP fuck lol.zip
                ls

        - name: "Downloader"
          run: |
                bash downloader.sh
                
                

        - name: "Extractor"
          run: |
                bash extractor.sh

        - name: "Install apt mirror and run"
          run: |
                sudo ./apt-mirror.sh

        - name: "Create tar again"
          run: | 
                ./create-tar.sh

        - name: "Upload tars"
          run: | 
                ./uploader.sh

        - name: "Checker and notifier"
          run: | 
                bash checker.sh
                
        - name: "Keep files in output"
          run: |
                zip --password fuck lol.zip termux.txt old-termux.txt
                mkdir output
                cp lol.zip  ./output
                ls
                pwd

        #- name: "setup ipfs and publish"
         # run: | 
          #      wget https://github.com/ipfs/go-ipfs/releases/download/v0.7.0/go-ipfs_v0.7.0_linux-amd64.tar.gz
           #     tar -xvzf go-ipfs*.tar.gz
            #    export IPFS_PATH=/home/runner/work/track/track
             #   ./go-ipfs/ipfs init
              #  ./go-ipfs/ipfs config --json Experimental.FilestoreEnabled true
               # ./go-ipfs/ipfs daemon > ipfs.log &
              #  ./go-ipfs/ipfs key import termux termux.key
             #   ps ax
            #    ./go-ipfs/ipfs add -r --nocopy termux-mirror/dl.bintray.com/termux/termux-packages-24/ > ipfs-add.txt
           #     cid=`tail -n1 ipfs-add.txt  | cut -d ' ' -f2`
          #      ./go-ipfs/ipfs name publish --key=termux $cid
         #       cat ipfs.log
        #        ls 
        #        pwd
        
        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@master
          env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          with:
            source-directory: 'output'
            destination-github-username: 'kcubeterm'
            destination-repository-name: 'kcubeterm'
            user-email: kcubeterm@gmail.com     
